### ISSUE TITLE
Choose page format template

### ISSUE THREAD

**Issue by IvanR-Vecerina** [dil-classroom/projet-dil-peer_debleser_marques_vecerina#23]
Decide and provide a format user will have to use for input.

Prerequisites: 
- [x] One out of ( #18 , #19 , #20 )
- [x] One out of ( #21 , #22 )

**Comment by Androto9** [comment]
For the format with decided to separate the yaml part from the md part with "{---}". By using the split() method in the Files library it'll be easier to get each specification for future treatment.
