### ISSUE TITLE
Start and plan the template engine

### ISSUE THREAD

**Issue by IvanR-Vecerina** [dil-classroom/projet-dil-peer_debleser_marques_vecerina#44]
look into template engine (i.e. handlebar: https://github.com/jknack/handlebars.java, or other)
read the documentation and lookup examples so as to plan the structure for it.

**Comment by Androto9** [comment]
Estimate time for task 4 weeks

**Comment by Androto9** [comment]
A refactoring will be done for this part. We'll try to have a cleaner code
Expected time 4 hours
